[package]
name = "leetgo-rs"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Rust test utils for leetgo"
homepage = "https://github.com/j178/leetgo"

[dependencies]
anyhow = "1.0.70"
serde = "1.0.156"
serde_json = "1.0.94"
